name: Test

on:
  push:
    branches:
      - '*'

jobs:
  install-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - run: yarn
      - uses: ./
      - run: curl https://setup-lando.lndo.site
  install-older:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - run: yarn
      - uses: ./
        with:
          version: v3.0.26
      - run: curl https://setup-lando.lndo.site
  with-healthchek:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - run: yarn
      - uses: ./
        with:
          healthcheck: https://setup-lando.lndo.site
      - run: curl https://setup-lando.lndo.site
